<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Infra\InfraDAL\InfraDbService\InfraDbService.csproj" />
    <ProjectReference Include="..\..\FinnasDbService\FinnasDbService\FinnasDbService.csproj" />
    <ProjectReference Include="..\..\FinnasLogicService\FinnasLogicService\FinnasLogicService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="InfraAuthWS">
      <HintPath>..\..\..\..\Infra\InfraAuthWS\InfraAuthWS\bin\Debug\net10.0\InfraAuthWS.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
